"""小说/剧本Schema定义包"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum

from ._enums import (
    ContentType,
    ProjectType,
    ProjectStatus,
    ChapterStatus,
)

from ._config import (
    NovelConfig,
    SeriesScriptConfig,
    MovieScriptConfig,
    ScriptConfig,
)

from ._project import (
    NovelProjectCreate,
    ScriptProjectCreate,
    NovelProjectUpdate,
    NovelProjectResponse,
    NovelProjectListResponse,
    OutlineUploadResponse,
)

from ._chapter import (
    DirectoryGenerateRequest,
    ChapterMetadata,
    SceneMetadata,
    SceneGenerateRequest,
    SceneGenerateResponse,
    ScriptDirectoryRequest,
    EpisodeDirectory,
    ScriptDirectoryResponse,
    ChapterGenerateRequest,
    ChapterGenerateResponse,
    ChapterContentResponse,
    ChapterContentUpdate,
    ChapterListResponse,
    DirectoryUpdateRequest,
    DirectoryResponse,
    ExportRequest,
    ExportResponse,
    GenerationProgress,
    BatchGenerateRequest,
    BatchGenerateResponse,
    CharacterInfo,
    CharacterListResponse,
)

from ._outline import (
    EpisodeOutlineScene,
    EpisodeOutlineBase,
    EpisodeOutlineCreate,
    EpisodeOutlineUpdate,
    EpisodeOutlineResponse,
    EpisodeOutlineListResponse,
    EpisodeOutlineGenerateRequest,
    ChapterOutlineBase,
    ChapterOutlineCreate,
    ChapterOutlineUpdate,
    ChapterOutlineResponse,
    ChapterOutlineListResponse,
    ChapterOutlineGenerateRequest,
    SceneOutlineBase,
    SceneOutlineCreate,
    SceneOutlineUpdate,
    SceneOutlineResponse,
    SceneOutlineListResponse,
    SceneOutlineGenerateRequest,
)

from ._style import (
    VocabularyProfile,
    SentenceStructureProfile,
    NarrativeStyleProfile,
    DescriptionStyleProfile,
    DialogueStyleProfile,
    EmotionalExpressionProfile,
    StructuralFeaturesProfile,
    StyleProfile,
    ExampleTransformation,
    StyleDocumentResponse,
    StyleDocumentUpdate,
)

__all__ = [
    "ContentType",
    "ProjectType",
    "ProjectStatus",
    "ChapterStatus",
    "NovelConfig",
    "SeriesScriptConfig",
    "MovieScriptConfig",
    "ScriptConfig",
    "NovelProjectCreate",
    "ScriptProjectCreate",
    "NovelProjectUpdate",
    "NovelProjectResponse",
    "NovelProjectListResponse",
    "OutlineUploadResponse",
    "DirectoryGenerateRequest",
    "ChapterMetadata",
    "SceneMetadata",
    "SceneGenerateRequest",
    "SceneGenerateResponse",
    "ScriptDirectoryRequest",
    "EpisodeDirectory",
    "ScriptDirectoryResponse",
    "ChapterGenerateRequest",
    "ChapterGenerateResponse",
    "ChapterContentResponse",
    "ChapterContentUpdate",
    "ChapterListResponse",
    "DirectoryUpdateRequest",
    "DirectoryResponse",
    "ExportRequest",
    "ExportResponse",
    "GenerationProgress",
    "BatchGenerateRequest",
    "BatchGenerateResponse",
    "CharacterInfo",
    "CharacterListResponse",
    "EpisodeOutlineScene",
    "EpisodeOutlineBase",
    "EpisodeOutlineCreate",
    "EpisodeOutlineUpdate",
    "EpisodeOutlineResponse",
    "EpisodeOutlineListResponse",
    "EpisodeOutlineGenerateRequest",
    "ChapterOutlineBase",
    "ChapterOutlineCreate",
    "ChapterOutlineUpdate",
    "ChapterOutlineResponse",
    "ChapterOutlineListResponse",
    "ChapterOutlineGenerateRequest",
    "SceneOutlineBase",
    "SceneOutlineCreate",
    "SceneOutlineUpdate",
    "SceneOutlineResponse",
    "SceneOutlineListResponse",
    "SceneOutlineGenerateRequest",
    "VocabularyProfile",
    "SentenceStructureProfile",
    "NarrativeStyleProfile",
    "DescriptionStyleProfile",
    "DialogueStyleProfile",
    "EmotionalExpressionProfile",
    "StructuralFeaturesProfile",
    "StyleProfile",
    "ExampleTransformation",
    "StyleDocumentResponse",
    "StyleDocumentUpdate",
]